<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>ink</string>
    <key>scopeName</key>
    <string>source.ink</string>
    <key>fileTypes</key>
    <array>
      <string>ink</string>
      <string>ink2</string>
    </array>
    <key>uuid</key>
    <string>5a0f60ba-87b8-4fa9-854c-6bf41f74bd98</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*(={2,})\s*(function)?\s*(\w+)\s*(\([^)]*\))?\s*(={1,})?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.punctuation</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.function</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.knot</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>markup.punctuation</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.knot.declaration</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*(=)\s*(\w+)\s*(\([^)\n]*\))?\s*$</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.punctuation</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.stitch</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.stitch.declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#choice</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#gather</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>tag</key>
      <dict>
        <key>begin</key>
        <string>(#)\s*</string>
        <key>end</key>
        <string>\s*$\n*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.hashtag</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>entity.name.tag</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.documentation.json</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.json</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
          </dict>
        </array>
      </dict>
      <key>TODO</key>
      <dict>
        <key>match</key>
        <string>^\s*(?:(TODO\s*:)|(TODO\b))\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.todo.TODO</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.todo.TODO</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>comment.todo</string>
      </dict>
      <key>include</key>
      <dict>
        <key>begin</key>
        <string>^\s*((INCLUDE)\s*(\S*))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.include</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.include</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.other</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
      </dict>
      <key>external</key>
      <dict>
        <key>begin</key>
        <string>^\s*((EXTERNAL)\s*([\w_0-9]*\(\)))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.external</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.external</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
      </dict>
      <key>globalVAR</key>
      <dict>
        <key>begin</key>
        <string>^\s*((VAR|CONST)\s*(\w+))\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.variable.declaration</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>meta.variable.assignment</string>
      </dict>
      <key>choice</key>
      <dict>
        <key>begin</key>
        <string>^\s*((?:[\*\+]\s?)+)\s*(\(\s*(\w+)\s*\))?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.weaveBullet.choice</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.label</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.label</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>choice</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\[)((?:[^\]]|\\\[|\])*)(\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.weaveBracket</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.content</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.weaveBracket</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#divert</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mixedContent</string>
          </dict>
        </array>
      </dict>
      <key>gather</key>
      <dict>
        <key>match</key>
        <string>^\s*((?:-\s*)+)(?!&gt;)(\(\s*(\w+)\s*\))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.weaveBullet.gather</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.label</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.label</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.gather</string>
      </dict>
      <key>multiLineLogic</key>
      <dict>
        <key>begin</key>
        <string>^\s*(\{)([\w_\s\*\/\-\+\&amp;\|\%\&lt;\&gt;\.\(\)]+(:))?(?=[^}]+$)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.logicBegin</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.logic</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.logic</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>meta.multilineLogicInner</string>
        <key>name</key>
        <string>meta.multilineLogic</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*else\s*\:</string>
            <key>name</key>
            <string>conditional.else</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\s*(-)\s?[^:]+(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$\n?</string>
            <key>name</key>
            <string>conditional.clause</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#mixedContent</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>inlineConditional</key>
      <dict>
        <key>begin</key>
        <string>(\{)[^:\|\}]+:</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineConditionalStart</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineConditionalEnd</string>
          </dict>
        </dict>
        <key>name</key>
        <string>entity.inlineConditional</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\|</string>
            <key>name</key>
            <string>keyword.operator.inlineConditionalBranchSeparator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mixedContent</string>
          </dict>
        </array>
      </dict>
      <key>inlineSequence</key>
      <dict>
        <key>begin</key>
        <string>(\{)\s*(~|&amp;|!|\$)?(?=([^\|]*\|(?!\|)[^\}]*)\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineSequenceStart</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineSequenceTypeChar</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineSequenceEnd</string>
          </dict>
        </dict>
        <key>name</key>
        <string>entity.inlineSequence</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\|(?!\|)</string>
            <key>name</key>
            <string>keyword.operator.inlineSequenceSeparator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mixedContent</string>
          </dict>
        </array>
      </dict>
      <key>inlineLogic</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineLogicStart</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.inlineLogicEnd</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.logic</string>
      </dict>
      <key>logicLine</key>
      <dict>
        <key>match</key>
        <string>\s*(~\s*.*)$</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.logic</string>
          </dict>
        </dict>
      </dict>
      <key>divert</key>
      <dict>
        <key>match</key>
        <string>(-&gt;|&lt;-)\s*((?:(DONE)|(END)|(\w+))(?:\s*\.\s*(?:\w+))*\s*(?:\([^\)]+\))?)?</string>
        <key>name</key>
        <string>meta.divert</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.divert</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.done</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.end</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.divertTarget</string>
          </dict>
        </dict>
      </dict>
      <key>mixedContent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inlineConditional</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inlineSequence</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inlineLogic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#divert</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&gt;</string>
            <key>name</key>
            <string>constant.glue</string>
          </dict>
        </array>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#include</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#external</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#TODO</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#globalVAR</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#choice</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#gather</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#multiLineLogic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#endOfSection</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#logicLine</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mixedContent</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>