<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ink</string>
		<string>ink2</string>
	</array>
	<key>name</key>
	<string>ink2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(={1,})\s*(\w+)\s*(\([\w\s,]+\))?\s*(={1,})?\s*$</string>
			<key>name</key>
			<string>meta.knot.declaration</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((?:[\*\+]\s?)+)\s*(\(\s*(\w+)\s*\))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.choiceBullet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>choice</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.content</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)([^\]]*)(\])</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#divert</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixedContent</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gatherBullet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?:-\s?)+)\s*(?:\(\s*(\w+)\s*\))?</string>
			<key>name</key>
			<string>entity.gather</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>choice</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?:[\*\+]\s?)+)\s*(\(\s*(\w+)\s*\))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.choiceBullet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>choice</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.content</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)([^\]]*)(\])</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#divert</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixedContent</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.json</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.json</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.json</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</array>
		</dict>
		<key>divert</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.divert</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.divertTarget</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(-&gt;|=&gt;|==&gt;)\s*([\w\.]+)?</string>
		</dict>
		<key>endOfSection</key>
		<dict>
			<key>end</key>
			<string>$</string>
			<key>match</key>
			<string>\s*(~\s*){2,}\s*</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>inlineConditional</key>
		<dict>
			<key>begin</key>
			<string>(\{)[^:\|\}]+:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineConditionalStart</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineConditionalEnd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.inlineConditional</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.inlineConditionalBranchSeparator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixedContent</string>
				</dict>
			</array>
		</dict>
		<key>inlineLogic</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineLogicStart</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineLogicEnd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.logic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#innerLogic</string>
				</dict>
			</array>
		</dict>
		<key>inlineSequence</key>
		<dict>
			<key>begin</key>
			<string>(\{)\s*(~|&amp;|!|\$)?(?=([^\|]*\|(?!\|)[^\}]*)\})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineSequenceStart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineSequenceTypeChar</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.inlineSequenceEnd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.inlineSequence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|(?!\|)</string>
					<key>name</key>
					<string>keyword.operator.inlineSequenceSeparator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixedContent</string>
				</dict>
			</array>
		</dict>
		<key>innerLogic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(choice_count|beats_since)\b\s*\([^\)]*\)</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\w+\b\s*\((?:[^\)]*)\)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b(and|or|not|mod)\b)|\!\=|\!|&amp;&amp;|\|\||==|&lt;=|&gt;=|&lt;|&gt;|\+|-|\*|/|\+\+|\-\-|%</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>logicLine</key>
		<dict>
			<key>begin</key>
			<string>\s*(~)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>entity.logicLine</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.varDeclaration</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(var)\s+(\w+)(?:\s*(=))?</string>
					<key>name</key>
					<string>meta.logic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.filename</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(include)\s+(.*)\s*$</string>
					<key>name</key>
					<string>entity.include</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(done|return)\s*(\([^\)]*\))?</string>
					<key>name</key>
					<string>entity.returnStatement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#innerLogic</string>
				</dict>
			</array>
		</dict>
		<key>mixedContent</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inlineConditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inlineSequence</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inlineLogic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#divert</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;</string>
					<key>name</key>
					<string>constant.glue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.content</string>
				</dict>
			</array>
		</dict>
		<key>multiLineLogic</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\{)([\w_\s\*\/\-\+\&amp;\|\%\&lt;\&gt;]+(:))?(?=[^}]+$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.multilineLogicInner</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.multilineLogic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(-)\s?[^:]+(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>conditional.clause</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mixedContent</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#statements</string>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#choice</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiLineLogic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#endOfSection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logicLine</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mixedContent</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ink</string>
	<key>uuid</key>
	<string>5a0f60ba-87b8-4fa9-854c-6bf41f74bd98</string>
</dict>
</plist>
