# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Logseq Publish
        # You may pin to the exact commit or the version.
        # uses: pengx17/logseq-publish@ba73f51ba89dc54727bddf05d976d65e5cdef376
        uses: pengx17/logseq-publish@v0.1
        with:
          # export source
          src: Documentation/runtime-specification # default is 
          # export destination
          dest: public # default is www
          # Logseq version to use. Note, not all version are supported. Use "master" if you are not sure what to put here

          version: master # default is master
          # Whether or not to generate trace file for debugging.  

          trace: true # optional, default is true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
